name: Compile Contrib Library for Rust 1.85.0

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # 使用一个更通用的旧版本 Ubuntu 环境进行编译
    runs-on: ubuntu-20.04

    steps:
      # ... 后面的内容保持不变 ...
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.85.0
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libmeme-generator-contrib-so-1.85.0
          path: target/release/libmeme_generator_contrib.so
