name: Compile Contrib Library for Rust 1.85.0

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.85.0
          override: true

      # 在编译命令后添加 -vv 参数以获取详细日志
      - name: Build
        run: cargo build --release -vv

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libmeme-generator-contrib-so-1.85.0
          path: target/release/libmeme_generator_contrib.so
