name: Compile Contrib Library for Rust 1.88.0 on Ubuntu 22.04

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # 关键改动：将编译器版本更新到 1.88.0 以匹配您的新环境
          toolchain: 1.88.0
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libmeme-generator-contrib-so-1.88.0
          path: target/release/libmeme_generator_contrib.so
