name: Compile Contrib Library for Rust 1.85.0 on Ubuntu 22.04

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # 关键改动：指定与您服务器完全一致的 Ubuntu 22.04 版本
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.85.0
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libmeme-generator-contrib-so-ubuntu22.04
          path: target/release/libmeme_generator_contrib.so
